CREATE OR REPLACE VIEW DPC AS
SELECT DNUM, COUNT(*) AS PJCNT
FROM Projects
GROUP BY DNUM;

SELECT DNAME AS DepartmentName, E.PSCNT AS PersonCount
FROM Departments
INNER JOIN (
    SELECT DNUM
    FROM DPC
    WHERE PJCNT = (SELECT MAX(PJCNT) FROM DPC) ) D
    ON Departments.DNUMBER = D.DNUM
INNER JOIN (
    SELECT DNO, COUNT(*) AS PSCNT
    FROM Employees
    GROUP BY DNO) E
    ON Departments.DNUMBER = E.DNO;
