-- Q1(a)
SELECT FNAME, LNAME
FROM EMPLOYEES
WHERE SALARY > SOME (
    SELECT SALARY 
    FROM EMPLOYEES e
    WHERE e.DNO IN (
        SELECT DNUMBER
        FROM DEPARTMENTS
        WHERE DNAME = 'ConsProd'
    )
);

SELECT FNAME, LNAME
FROM EMPLOYEES
WHERE SALARY > SOME (
    SELECT SALARY 
    FROM EMPLOYEES e, DEPARTMENTS d
    WHERE e.DNO = d.DNUMBER AND d.DNAME = 'ConsProd'
);


-- Q1(b)
SELECT FNAME, CPR, EMPLOYEES.DNO AS DepartmentNumber, max_salary AS MaxSalary
FROM EMPLOYEES, (
    SELECT e.DNO, MAX(e.SALARY) AS max_salary
    FROM EMPLOYEES e, DEPARTMENTS d
    WHERE e.DNO = d.DNUMBER
    GROUP BY e.DNO
) max_sal_tab
WHERE EMPLOYEES.DNO=max_sal_tab.DNO;

-- Q1(c)
SELECT d.DNAME, COUNT(*) AS male_cnt
FROM EMPLOYEES e, DEPARTMENTS d
WHERE d.DNUMBER = e.DNO AND e.SEX = 'M' AND e.DNO IN (
    SELECT DNO
    FROM EMPLOYEES
    GROUP BY DNO
    HAVING AVG(SALARY) > 27000
)
GROUP BY d.DNUMBER;

-- Q1(d)
SELECT EMPLOYEES.DNO DepartmentNumber, COUNT(*)
FROM EMPLOYEES,
(
    SELECT DNO, AVG(SALARY) avg_sal
    FROM EMPLOYEES
    GROUP BY DNO
) DNO_AVGSAL
WHERE EMPLOYEES.SALARY > DNO_AVGSAL.avg_sal AND EMPLOYEES.DNO = DNO_AVGSAL.DNO
GROUP BY EMPLOYEES.DNO;

-- Q2(a)
CREATE TABLE Reservation (
    NO INT PRIMARY KEY,
    Available CHAR (1) NOT NULL
);

-- Q2(b1)
SELECT NO, FLOOR(NO/20) as row_num
FROM RESERVATION
WHERE AVAILABLE = 'Y';

-- Q2(b2)
SELECT NO, FLOOR(NO/20) as row_num
FROM RESERVATION 
WHERE AVAILABLE = 'N';

-- Q2(c)



-- Q2(d)
-- SELECT *
-- FROM EMPLOYEES e
-- INNER JOIN DEPARTMENTS d
-- ON e.DNO = d.DNUMBER
-- WHERE e.DNO = 10
-- ;
-- SELECT e.DNO, e.CPR
-- FROM EMPLOYEES e
-- GROUP BY e.DNO;
SELECT MAX(DNO)
FROM EMPLOYEES;

SELECT DNO != 10
FROM EMPLOYEES;

SELECT e1.DNO
FROM EMPLOYEES e1
INNER JOIN EMPLOYEES e2
on e1.DNO = e2.DNO;

SELECT e.DNO
FROM EMPLOYEES e
INTERSECT --minus union
SELECT e.DNO
FROM EMPLOYEES e
WHERE e.DNO = '10';
