-- rollback the changes
ROLLBACK;
ALTER SESSION SET nls_date_format='YYYY-MM-DD';

-- ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';


--3.1(a)
SELECT FNAME, LNAME, CPR, SALARY
FROM EMPLOYEES
WHERE FNAME = 'Tina';


--3.1(b)
UPDATE EMPLOYEES
SET SALARY = SALARY * 1.2
WHERE SALARY < 30000;
UPDATE EMPLOYEES
SET SALARY = SALARY * 1.15
WHERE SALARY >= 30000;


--3.1(d)
SELECT FNAME, BDATE
FROM EMPLOYEES
WHERE BDATE BETWEEN '1950-01-01' AND '1959-12-31';

--3.2(a)
CREATE OR REPLACE VIEW DP AS
SELECT DNUM, COUNT(*) AS PCOUNT
FROM PROJECTS
GROUP BY DNUM;

CREATE OR REPLACE VIEW DPMAX AS
SELECT * 
FROM DP
WHERE PCOUNT = (SELECT MAX(PCOUNT) FROM DP);

CREATE OR REPLACE VIEW DNO_PCOUNT AS
SELECT d.DNUM, COUNT(*) AS PCOUNT
FROM EMPLOYEES e
INNER JOIN DPMAX d
ON e.DNO = d.DNUM
GROUP BY d.DNUM;

SELECT d.DNAME, dp.DNUM, dp.PCOUNT
FROM DEPARTMENTS d
INNER JOIN DNO_PCOUNT dp 
ON d.DNUMBER = dp.DNUM;

--3.2(b)
CREATE OR REPLACE VIEW D_AVG_LARGER AS
SELECT e.DNO, AVG(e.SALARY) as AVG_SALARY
FROM EMPLOYEES e
INNER JOIN DEPARTMENTS d
ON e.DNO = d.DNUMBER
GROUP BY e.DNO
HAVING AVG(e.SALARY) > 27000;

CREATE OR REPLACE VIEW D_MALE_CNT AS
SELECT DNO, COUNT(*) AS MALE_NUM
FROM EMPLOYEES
WHERE SEX = 'M'
GROUP BY DNO;

SELECT d1.DNAME, d3.MALE_NUM
FROM DEPARTMENTS d1
INNER JOIN D_AVG_LARGER d2
ON d1.DNUMBER = d2.DNO
INNER JOIN D_MALE_CNT d3
ON d1.DNUMBER = d3.DNO;

--ensemble
SELECT d1.DNAME, d3.MALE_NUM
FROM DEPARTMENTS d1
INNER JOIN (
    SELECT e.DNO, AVG(e.SALARY) as AVG_SALARY
    FROM EMPLOYEES e
    INNER JOIN DEPARTMENTS d
    ON e.DNO = d.DNUMBER
    GROUP BY e.DNO
    HAVING AVG(e.SALARY) > 27000
) d2
ON d2.DNO = d1.DNUMBER
INNER JOIN (
    SELECT DNO, COUNT(*) AS MALE_NUM
    FROM EMPLOYEES
    WHERE SEX = 'M'
    GROUP BY DNO
) d3
ON d3.DNO = d1.DNUMBER;


--3.2(c)
CREATE OR REPLACE VIEW DNO_MAX AS
SELECT DNO, MAX(SALARY) as MAX_SALARY
FROM EMPLOYEES
GROUP BY DNO;

SELECT e.FNAME, e.CPR, e.DNO, d.MAX_SALARY
FROM EMPLOYEES e
-- INNER JOIN DNO_MAX d
LEFT JOIN DNO_MAX d 
ON e.DNO = d.DNO;

--ensemble
SELECT e.FNAME, e.CPR, e.DNO, d.MAX_SALARY
FROM EMPLOYEES e
-- INNER JOIN DNO_MAX d
LEFT JOIN (
    SELECT DNO, MAX(SALARY) as MAX_SALARY
    FROM EMPLOYEES
    GROUP BY DNO
) d 
ON e.DNO = d.DNO;


